# This is the file that generates and deploys https://www.roc-lang.org,
# which is served on Netlify.
#
# Netlify's docs for how this configuration file works:
# https://docs.netlify.com/routing/headers/#syntax-for-the-netlify-configuration-file
[build]
  publish = "build/"
  command = "bash netlify.sh"
  # Always build on push - see https://answers.netlify.com/t/builds-cancelled-for-a-new-branch-due-to-no-content-change/17169/2
  ignore = "/bin/false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # unsafe-eval is needed for wasm compilation in the repl to work on Safari and Chrome;
    # otherwise they block it.
    # TODO figure out how to tell Netlify to apply that policy only to the repl, not to everything.
    Content-Security-Policy = "default-src 'self'; img-src *; script-src 'self' 'unsafe-eval';"
    X-Content-Type-Options = "nosniff"

# Redirect roc-lang.org/authors to the AUTHORS file in this repo
#
# This is referenced in the LICENSE file, which says to see roc-lang.org/authors
# for a list of authors!
[[redirects]]
  from = "/authors"
  to = "https://github.com/rtfeldman/roc/blob/trunk/AUTHORS"
  force = true
  status = 302 # TODO once the repo is public, use status = 200 and this URL:
               # https://raw.githubusercontent.com/rtfeldman/roc/trunk/AUTHORS
               #
               # This way, roc-lang.org/authors will show the authors directly,
               # proxied from the current AUTHORS file on GitHub, no redirects.
